### ISSUE TITLE
pre_trained model 

### ISSUE THREAD

**Issue by SaltwaterLHL** [sniklaus/pytorch-spynet#11]
wget --timestamping http://content.sniklaus.com/github/pytorch-spynet/network-chairs-clean.pytorch
wget --timestamping http://content.sniklaus.com/github/pytorch-spynet/network-chairs-final.pytorch

What is the difference between the pre_train models ?

**Comment by sniklaus** [comment]
My apologies, but I have only converted the official pre-trained models while making sure that the output of my reimplementation matches the output of the official Torch implementation. Neither the paper nor the official repository seem to state what the difference between `chairsClean` and `chairsFinal` is.

**Comment by SaltwaterLHL** [comment]
Thanks for your answering.One more question is why the run.py inputs (tensorFirst and tensorSecond） are not be concated?
Does this have no effect on the final result?




在 2019-03-14 17:37:55，"Simon Niklaus" <notifications@github.com> 写道：


My apologies, but I have only converted the official pre-trained models while making sure that the output of my reimplementation matches the output of the official Torch implementation. Neither the paper nor the official repository seem to state what the difference between chairsClean and chairsFinal is.

**Comment by sniklaus** [comment]
I am afraid that I do not understand your question. At each pyramid level, the second image has to be warped according to the optical flow. How would concatenating the images help with this?
