### ISSUE TITLE
TypeError: grid_sample() got an unexpected keyword argument 'align_corners'

### ISSUE THREAD

**Issue by ShaofengZou** [sniklaus/pytorch-spynet#13]
It was triggered when running to 
````
tensorFlow = torch.nn.functional.interpolate(input=moduleNetwork(tensorPreprocessedFirst, tensorPreprocessedSecond), size=(intHeight, intWidth), mode='bilinear', align_corners=False)
````
How can l solve this problem? Is that a cause of low pytorch version?
Looking forward to your reply.

**Comment by sniklaus** [comment]
Which version of PyTorch are you using?

**Comment by ShaofengZou** [comment]
I have tried on ```1.0.0``` , ```1.0.1.post2``` and ```1.1.0```. None of these three versions successfully worked.

**Comment by sniklaus** [comment]
I just checked and `align_corners` got introduced to `grid_sample` with PyTorch `1.3.0`, so you can either meet this minimum version or remove the `align_corners` attribute from the `grid_sample` call.

**Comment by ShaofengZou** [comment]
All right. I have make it worked by adding ```align_corners``` to the ```grid_sample``` call.
Thank you very much!
