### ISSUE TITLE
Could you please provide the training scripts?

### ISSUE THREAD

**Issue by ProNoobLi** [sniklaus/pytorch-spynet#14]
The current repo only includes the inference scripts, so could we get the training thing?
I am interested in the implementation of the separate and independent training process of each residual flow level.

**Comment by sniklaus** [comment]
This is a reimplementation of the official Torch version: https://github.com/anuragranj/spynet

I am afraid that this reimplementation focuses purely on replicating the inference using the parameters from the official models. You will thus have to examine the Torch version for details on training.
