### ISSUE TITLE
Reimplementation in Tensorflow

### ISSUE THREAD

**Issue by prasangadhungel** [sniklaus/pytorch-spynet#16]
Thank you for the wonderful work.
Relying on this, our team has also pulled out similar work in tensorflow. The architecture is available at: https://github.com/tukilabs/Video-Compression-Net/blob/master/utils/network.py (class SpyNetwork) and the pre-trained model is available at: https://github.com/tukilabs/Video-Compression-Net/blob/master/checkpoints/spymodel.pkl . 

Thanks!

**Comment by sniklaus** [comment]
Thanks for posting this here so others can find it better!
