### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by puhuk** [sniklaus/pytorch-spynet#19]
Thank you for sharing your code.
I have a question with this.

What the list ([ 80, 73, 69, 72 ]) mean?
https://github.com/sniklaus/pytorch-liteflownet/blob/dae3b132452b05d4258d1da75eaa1021c5b2d720/run.py#L381

Thanks in advance

**Comment by sniklaus** [comment]
It means `PIEH` in ASCII and is required for a `.flo` file: https://vision.middlebury.edu/flow/code/flow-code/README.txt
