### ISSUE TITLE
error in demo

### ISSUE THREAD

**Issue by zgcsrwh** [sniklaus/pytorch-spynet#2]
Hello! I tried your demo but got this error. 
line 151, in forward

variableFlow=torch.autograd.Variable(data=torch.zeros(variableFirst[0].size(0),2,math.floor(variableFirst[0].size(2) / 2.0), math.floor(variableFirst[0].size(3) / 2.0)).cuda(), volatile=not self.training)

TypeError: torch.zeros received an invalid combination of arguments - got (int, int, float, float), but expected one of:
 * (int ... size)

I changed to "data=torch.zeros(variableFirst[0].size(0)/2,math.floor....)" but still not work. It seems there's something wrong with the ''size''. I'm new to deep learning, can you give some suggestion?

Thanks!

**Comment by sniklaus** [comment]
That could stem from using Python 2, you can try switching to Python 3 or casting the result from floor to an int.

**Comment by zgcsrwh** [comment]
Thanks a lot! It works fine now.
