### ISSUE TITLE
How to train spynet using pytorch?

### ISSUE THREAD

**Issue by StevenTony611** [sniklaus/pytorch-spynet#20]
How to train spynet using PyTorch?

This project only has test code for spynet, could you release train spynet code? 
Thank you very much!

**Comment by sniklaus** [comment]
I am afraid that I am not the author of SpyNet, I just ported the official Torch implementation to PyTorch (inference only). For the official implementation which also includes training, please see: https://github.com/anuragranj/spynet

**Comment by StevenTony611** [comment]
I want to know you how to train spynet using PyTorch,  because the official implementation uses Lua and I can't train spynet using PyTorch. 
If you could provide the training code of spynet, we will thank you very much！

**Comment by sniklaus** [comment]
I am afraid that I didn't train SpyNet in PyTorch, I just took the models trained in Torch and converted them to PyTorch.

**Comment by StevenTony611** [comment]
I know this matter，thank you for your answer！
