### ISSUE TITLE
getopt error 

### ISSUE THREAD

**Issue by wildug** [sniklaus/pytorch-spynet#21]
066636aa88d4e8b85df85f14923c51e4a655f741 introduced an error if run.py is run with 
`python run.py --model sintel-final --first ./images/first.png --second ./images/second.png --out ./out.flo`
taken from current README.md

**Comment by sniklaus** [comment]
I just fixed it in e742a97be73cb539fb95d5df55178e6281074656, thank you for bringing this up!
