### ISSUE TITLE
Invalid arguments in run.py in line 151.

### ISSUE THREAD

**Issue by fkdosilovic** [sniklaus/pytorch-spynet#3]
I'm getting the following error when I run:
`python run.py --model sintel-final --first ./images/first.png --second ./images/second.png --out ./out.flo`

Traceback (most recent call last):
  File "run.py", line 210, in <module>
    tensorOutput = estimate(tensorInputFirst, tensorInputSecond)
  File "run.py", line 192, in estimate
    tensorOutput.resize_(2, intHeight, intWidth).copy_(moduleNetwork(variableInputFirst, variableInputSecond).data[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "run.py", line 151, in forward
    variableFlow = torch.autograd.Variable(data=torch.zeros(variableFirst[0].size(0), 2, math.floor(variableFirst[0].size(2) / 2.0), math.floor(variableFirst[0].size(3) / 2.0)).cuda(), volatile=not self.training)
TypeError: torch.zeros received an invalid combination of arguments - got (int, int, float, float), but expected one of:
 * (int ... size)
      didn't match because some of the arguments have invalid types: (int, int, float, float)
 * (torch.Size size)

I was able to fix it by casting both math.floor calls to int.

**Comment by fkdosilovic** [comment]
Sorry, didn't see closed issues.

**Comment by sniklaus** [comment]
Thank you for bringing this up an no worries that you didn't see the other issue. Since this might happen again in the future, I took the initiative and updated the code accordingly. Thanks!
