### ISSUE TITLE
Training Architecture

### ISSUE THREAD

**Issue by haohang96** [sniklaus/pytorch-spynet#4]
How the every basic-module(a 5 layers convolution network) trains? I don't find your train part in your files.

**Comment by sniklaus** [comment]
I am afraid that you have to add that part yourself. The provided code focuses on inference, but there should be no major hurdle to add the training portion. You should make sure to have a look at the [repository of the authors of SPyNet](https://github.com/anuragranj/spynet), they are providing the training part that you could adapt accordingly.
