### ISSUE TITLE
Error when running the command

### ISSUE THREAD

**Issue by Wazaki-Ou** [sniklaus/pytorch-spynet#5]
I tried to run the command for a test with the 2 pictures provided (I installed pytorch on Anaconda) and I got the following error:

```
Traceback (most recent call last):
  File "run.py", line 166, in <module>
    moduleNetwork = Network().cuda()
  File "run.py", line 133, in __init__
    self.moduleBasic = torch.nn.ModuleList([ Basic(intLevel) for intLevel in range(6) ])
  File "run.py", line 133, in <listcomp>
    self.moduleBasic = torch.nn.ModuleList([ Basic(intLevel) for intLevel in range(6) ])
  File "run.py", line 100, in __init__
    self.moduleBasic[intConv * 2].weight.data.copy_(torch.utils.serialization.load_lua('./models/modelL' + str(intLevel + 1) + '_' + arguments_strModel  + '-' + str(intConv + 1) + '-weight.t7'))
RuntimeError: The expanded size of the tensor (7) must match the existing size (0) at non-singleton dimension 3
```

Do you know what could be the reason for this ? thank you !!

**Comment by sniklaus** [comment]
Which version of PyTorch are you using?

**Comment by Wazaki-Ou** [comment]
@sniklaus I am using 0.4.0
While looking for a solution, I found that many people had a similar issue (same runtimeerror) with this release. I will try to modify the lines like they suggested and see if it works. Meanwhile, any suggestion is very welcome. Thank you !!

**Comment by sniklaus** [comment]
I updated the code to 0.4.0 which might resolve this issue. Could you give it a try again?

**Comment by Wazaki-Ou** [comment]
I tried again with the updated code but I keep getting the same error.

**Comment by sniklaus** [comment]
I am unfortunately not able to determine what is causing this issue. It apparently cannot load the weights from the pre-trained model, but that is all I can tell. Please keep us updated should you be able to resolve this issue. Thanks!

**Comment by Wazaki-Ou** [comment]
I surely will. Thank you for your replies.

**Comment by Wazaki-Ou** [comment]
A friend also tried from his machine and he gets the same problem. This is a link to similar error that happens while using Yolo. I think it might indeed be a problem in PyTorch 0.4.0. Maybe it can help you understand the error.
https://github.com/marvis/pytorch-yolo2/issues/84
Meanwhile, would it be possible to make it work with previous versions of PyTorch? I will just downgrade mine to use spynet. Thanks again !!

**Comment by sniklaus** [comment]
I am surprised that I am not experiencing the same issue. How did you install PyTorch, from the sources or are you using pre-built binaries?

If you want to give version 0.3.1 of PyTorch a try, just make sure to use the [commit](https://github.com/sniklaus/pytorch-spynet/tree/dd0b2e28eb3efb0b05f2dc3dee178bcea32eba92) from two months ago.

**Comment by Wazaki-Ou** [comment]
I installed it through anaconda using conda install. Could it be a python related issue? I am using python 3.6. Sure I will give it a try and let you know !!

**Comment by sniklaus** [comment]
I am using the Anaconda build as well, I am using Python 3.5 though. While there are different pre-built PyTorch binaries for Python 3.5 and Python 3.6, I would be surprised if one of them shows this behavior and the other one doesn't.
