### ISSUE TITLE
Can you provide me your flow rendering code?

### ISSUE THREAD

**Issue by Lotayou** [sniklaus/pytorch-spynet#8]
I write a simple flow-rendering function based on opencv tutorial. The result looks like this:
![out_flow_image](https://user-images.githubusercontent.com/33449901/47255155-1a3e9e00-d49f-11e8-923b-b1580e66d91b.png)

It looks the same but the color palette is ugly to me. Can you share your flow rendering code with me so I can generate visualized results just like on your github page?

Thanks!

**Comment by sniklaus** [comment]
I am afraid that the code in question originates from the Middlebury benchmark for optical flow, and I am not sure whether I am allowed to share it. However, you could get in touch with Daniel Scharstein and kindly ask him to share it with you as well.

**Comment by ryanxingql** [comment]
This code is helpful:
https://github.com/Johswald/flow-code-python/blob/master/computeColor.py
